const Types = {
	GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
	GET_COUNTRIES_DETAILS: 'GET_COUNTRIES_DETAILS',
	GET_COUNTRIES_FAIL: 'GET_COUNTRIES_FAIL',

	GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
	GET_COUNTRY_DETAILS: 'GET_COUNTRY_DETAILS',
	GET_COUNTRY_FAIL: 'GET_COUNTRY_FAIL',

	FILTER_REQUEST: 'FILTER_REQUEST',
	FILTER_SUCCESS: 'FILTER_SUCCESS',
	FILTER_FAIL: 'FILTER_FAIL',
	FILTER_RESET: 'FILTER_RESET',

};

export default Types;
